DELETE http://localhost:8080/events/1/register
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzQ2MzgzMjg2LCJ1c2VySWQiOjJ9._6kCgIgCQachWCq3nq_Hgm1vgHb0Kw-GGD5iB2-MD3w